colorScheme = "granny"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
mainSections = ["projects", "journal", "troubleshooting", "life"]

[homepage]
layout = "custom"
showRecent = true
showRecentItems = 6
cardView = true
cardViewScreenWidth = 1024
homepageImage = "img/homepage-bg.svg"

[header]
layout = "basic"
showTitle = true

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[article]
showDate = true
showAuthor = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showWordCount = false
showComments = false

[list]
showSummary = true
showCards = true
showDate = true
showTableOfContents = false
showTaxonomies = true
