baseURL = "https://granny-studio.github.io/granny-studio-blog/"
locale = "ko-KR"
defaultContentLanguage = "ko"
title = "Granny Studio"
enableRobotsTXT = true
summaryLength = 30

[pagination]
pagerSize = 10

[taxonomies]
tag = "tags"
category = "categories"
project = "projects"

[module]
[[module.imports]]
path = "github.com/nunocoracao/blowfish/v2"
